"""
pdf_report.py
-------------
Generates a professional PDF fraud detection report
from batch analysis results using fpdf2.

Install: pip install fpdf2
"""

from fpdf import FPDF
from datetime import datetime
import pandas as pd


class FraudReport(FPDF):
    """Custom PDF class with header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, "NLP-Based Financial Fraud Detection Report", align="C")
        self.ln(4)
        self.set_draw_color(180, 180, 180)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by NLP Fraud Detection System", align="C")


def generate_pdf_report(
    results_df: pd.DataFrame,
    total: int,
    high: int,
    medium: int,
    low: int,
    best_model_name: str,
    model_f1: float,
) -> bytes:
    """
    Generates a PDF report from batch analysis results.

    Parameters
    ----------
    results_df      : DataFrame with columns [Transaction Text, Risk Score, Risk Level, Signals, Flagged]
    total           : total transactions analysed
    high/medium/low : counts per risk level
    best_model_name : name of the ML model used
    model_f1        : F1 score of the model

    Returns
    -------
    bytes : raw PDF content ready for st.download_button
    """

    # Convert all inputs to plain Python types to avoid fpdf2 errors
    total    = int(total)
    high     = int(high)
    medium   = int(medium)
    low      = int(low)
    model_f1 = float(model_f1)

    # Reset index so we always have clean 0-based integer index
    results_df = results_df.reset_index(drop=True)

    pdf = FraudReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Meta info ---
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}", ln=True)
    pdf.cell(0, 6, f"Model used: {best_model_name}  |  F1 Score: {model_f1:.3f}", ln=True)
    pdf.ln(4)

    # --- Summary box ---
    pdf.set_fill_color(245, 245, 245)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Executive Summary", ln=True, fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    summary_lines = [
        f"Total transactions analysed : {total}",
        f"High risk (flagged)         : {high}  ({round(high / total * 100, 1) if total else 0}%)",
        f"Medium risk                 : {medium}  ({round(medium / total * 100, 1) if total else 0}%)",
        f"Low risk (safe)             : {low}  ({round(low / total * 100, 1) if total else 0}%)",
    ]
    for line in summary_lines:
        pdf.cell(0, 7, line, ln=True)
    pdf.ln(4)

    # --- Flagged transactions ---
    flagged = results_df[results_df["Flagged"] == True].reset_index(drop=True)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(245, 245, 245)
    pdf.cell(0, 8, f"Flagged HIGH RISK Transactions ({len(flagged)})", ln=True, fill=True)
    pdf.ln(2)

    if flagged.empty:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 7, "No transactions flagged as HIGH risk.", ln=True)
    else:
        # Use enumerate so count is always a clean integer
        for count, (_, row) in enumerate(flagged.iterrows(), start=1):
            pdf.set_fill_color(255, 235, 235)
            pdf.set_draw_color(200, 100, 100)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(100, 20, 20)
            pdf.cell(
                0, 6,
                f"Transaction #{count}  |  Risk Score: {float(row['Risk Score']):.1f}  |  Signals: {int(float(row['Signals']))}",
                ln=True, fill=True, border=1
            )

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 40)

            text = str(row["Transaction Text"])
            if len(text) > 120:
                text = text[:120] + "..."
            pdf.multi_cell(0, 6, text, border="LRB")
            pdf.ln(2)

    pdf.ln(4)

    # --- All results table ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Full Results Table", ln=True, fill=True)
    pdf.ln(2)

    # Table header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(220, 220, 220)
    pdf.set_text_color(30, 30, 30)
    col_widths = [100, 22, 25, 20, 22]
    headers    = ["Transaction Text", "Risk Score", "Risk Level", "Signals", "Flagged"]
    for header, w in zip(headers, col_widths):
        pdf.cell(w, 7, header, border=1, fill=True, align="C")
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 8)
    for _, row in results_df.iterrows():
        risk = str(row["Risk Level"])
        if risk == "HIGH":
            pdf.set_fill_color(255, 220, 220)
        elif risk == "MEDIUM":
            pdf.set_fill_color(255, 243, 205)
        else:
            pdf.set_fill_color(220, 255, 220)

        text = str(row["Transaction Text"])
        if len(text) > 55:
            text = text[:55] + "..."

        pdf.set_text_color(30, 30, 30)
        pdf.cell(col_widths[0], 6, text,                                       border=1, fill=True)
        pdf.cell(col_widths[1], 6, f"{float(row['Risk Score']):.1f}",          border=1, fill=True, align="C")
        pdf.cell(col_widths[2], 6, risk,                                       border=1, fill=True, align="C")
        pdf.cell(col_widths[3], 6, str(int(float(row["Signals"]))),            border=1, fill=True, align="C")
        pdf.cell(col_widths[4], 6, "YES" if row["Flagged"] else "NO",          border=1, fill=True, align="C")

        pdf.ln()

    import tempfile, os
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        tmp_path = tmp.name
    pdf.output(tmp_path)
    with open(tmp_path, "rb") as f:
        pdf_bytes = f.read()
    os.unlink(tmp_path)
    return pdf_bytes